title: HES-SO Open Science Training Material
description: Learning materials for Open Science
theme: just-the-docs

url: https://aislab-hevs.github.io/open-science-training

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
